
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 1MB
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://3.36.184.78:3306/?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
      username: root
      password: dhdnrjrkwmdk1!
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      sql-script-encoding: UTF-8
      idleTimeout: 170000
      maxLifetime: 180000
      connection-timeout: 5000
      validation-timeout: 10000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
      port: 35729  

logging:
  level:
    com:
      zaxxer:
        hikari: TRACE
        HikariConfig: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
            
octet:
    url: https://dev.blockchainapi.pro/v1/
    auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHgiOjUyMywiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTg5NzMzNTYsImV4cCI6MTYyNjc0OTM1NiwiaXNzIjoibm9kZS5oZWxhbnQifQ.Ryn-2yVtK_SrRV6S4DEXFfvN2dmYF_0EGdl1Kg3XpvQ
    passphrase: Onetop135@$^
    privateKey: 802ea7441f7a99298a7674116b69ef563dbd4f2f790264b536bd9cccea945b3ddaba2f8f41648e2298818af2d67d05de72ede112f63f90cfa774e46d6d715bc56342c13c56c2719d5f591aa39579683659eda4a8577469e63a0b077438e375b3a176e88a48db2f98ff7304958b1426dfc0ca8b84c87bef109a5f9d69d7de298aa289e202e5f026cd5ff0a9f328273a7ed1e6423ce5c175eca2747975ebc5d983714ac74daa5f793ce7383eb875067dd777d9fc7c2e7de275e7ddf6063509120678873ad0ae6ef45ebed579124fcacffd5c13a14926eb70e47c6e5d12081de3129ec2ce17f159a39c87756265b95136f143306a49b6698d6de1a3a2bef2a948075165f34a90c0a23424fe39fc1166f5127f1

aws-email:
  accessKey: AKIAVJK3HF5BMNA73F6X
  secretKey: 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
  region: ap-northeast-2
  master: support@onetopinvest.com
---
server:
  port: 8000
  folder:
    banner-upload: /app/was/common-images
spring:
  profiles: default
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://3.36.184.78:3306/?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
      username: root
      password: dhdnrjrkwmdk1!  

# 출금 및 OTP KEY 확인 서버 주소
webadmin:
  balancenoti:
    addr: http://127.0.0.1:8182
  mailsender:
    addr: http://dev-mail-sender.lucky7.love
    txid:
      addr: luckysevenorg@gmail.com
  image:
    addr: http://image.onetopinvest.com


---
server:
  port: 8000
  folder:
    banner-upload: /app/was/common-images

spring:
  profiles: development
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
      username: root
      password: dhdnrjrkwmdk1!  

# 출금 및 OTP KEY 확인 서버 주소
webadmin:
  balancenoti:
    addr: http://127.0.0.1:8182
  mailsender:
    addr: http://dev-mail-sender.lucky7.love
    txid:
      addr: luckysevenorg@gmail.com
  image:
    addr: http://image.onetopinvest.com


---
server:
  port: 8000
  folder:
    banner-upload: /app/was/common-images

spring:
  profiles: production
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://onetop.cpruisxjq7je.ap-northeast-2.rds.amazonaws.com:3306/?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: wallet
      password: dkanrjsk135!#%

# 출금 및 OTP KEY 확인 서버 주소
webadmin:
  balancenoti:
    addr: http://172.31.55.94:8182
  mailsender:
    addr: https://mail-sender.lucky7.love
    txid:
      addr: luckysevenorg@gmail.com
  image:
    addr: https://image.onetopinvest.com